const image = (name) => `/tutorials/images/${name}.jpg`;
const pdf = (name) => `/tutorials/pdf/${name}.pdf`;

export const tutorialLibrary = [
  {
    id: 'create-mission',
    title: 'Créer une mission',
    introduction: 'Enregistrez une nouvelle intervention avec son lieu, ses dates et les informations utiles avant de rechercher un formateur.',
    category: 'Missions',
    audiences: ['organization'],
    public: true,
    duration: '3 min',
    pdf: pdf('Clementplane_Tutoriel_Creer_Une_Mission'),
    steps: [
      { title: 'Ouvrir le formulaire', description: 'Depuis « Missions », cliquez sur « Créer une mission ».', image: image('create-mission-1'), consequence: 'Le formulaire s’ouvre. Aucun formateur n’est contacté à ce stade.' },
      { title: 'Décrire la mission', description: 'Indiquez le client, votre référence interne, la formation et les besoins matériels.', image: image('create-mission-2'), consequence: 'Ces informations permettront d’identifier la mission et de rechercher les profils adaptés.' },
      { title: 'Ajouter le lieu et les dates', description: 'Renseignez la ville, les dates et les horaires de l’intervention.', image: image('create-mission-3'), consequence: 'Clementplane pourra vérifier la proximité et la disponibilité des formateurs.' },
      { title: 'Créer la mission', description: 'Relisez les informations puis validez le formulaire.', image: image('create-mission-4'), consequence: 'La mission est enregistrée « À pourvoir ». Aucun envoi automatique n’est effectué.' },
    ],
  },
  {
    id: 'search-trainer',
    title: 'Rechercher et consulter un formateur',
    introduction: 'Trouvez rapidement un profil dans votre réseau privé et vérifiez les informations utiles avant de le solliciter.',
    category: 'Formateurs',
    audiences: ['organization'],
    public: true,
    duration: '3 min',
    pdf: pdf('Clementplane_Tutoriel_Rechercher_Consulter_Formateur'),
    steps: [
      { title: 'Ouvrir « Formateurs »', description: 'Accédez à la liste privée des formateurs de votre organisme.', image: image('search-trainer-1'), consequence: 'Les autres organismes ne peuvent pas consulter cette liste.' },
      { title: 'Utiliser les filtres', description: 'Recherchez par nom, ville, compétence, matériel, statut ou disponibilité.', image: image('search-trainer-1'), consequence: 'La liste se réduit sans modifier les données des formateurs.' },
      { title: 'Ouvrir la fiche', description: 'Cliquez sur « Voir » pour consulter les informations professionnelles.', image: image('search-trainer-2'), consequence: 'Vous retrouvez les informations partagées et vos données internes.' },
      { title: 'Vérifier les disponibilités', description: 'Consultez le calendrier et la date de dernière mise à jour.', image: image('search-trainer-2'), consequence: 'Vous pouvez solliciter le formateur avec une information plus récente.' },
    ],
  },
  {
    id: 'propose-mission',
    title: 'Proposer une mission à un formateur',
    introduction: 'Sélectionnez un profil, choisissez le canal de contact et voyez ce qui apparaît ensuite côté formateur.',
    category: 'Parcours croisés',
    audiences: ['organization', 'trainer'],
    public: true,
    duration: '4 min',
    pdf: pdf('Clementplane_Tutoriel_Proposer_Mission_Formateur'),
    steps: [
      { title: 'Rechercher un profil', description: 'Depuis la mission, lancez la recherche selon le lieu, les dates et les compétences.', image: image('propose-mission-1'), consequence: 'Clementplane affiche les profils correspondant aux critères disponibles.' },
      { title: 'Sélectionner le formateur', description: 'Vérifiez le profil puis choisissez le formateur adapté.', image: image('propose-mission-2'), consequence: 'Le formateur est préparé pour la proposition, mais rien n’est encore envoyé.' },
      { title: 'Choisir le mode de contact', description: 'Choisissez l’envoi dans Clementplane ou consignez un contact externe.', image: image('propose-mission-3'), consequence: 'Le mode choisi détermine si Clementplane attend une réponse du formateur.' },
      { title: 'Suivre la proposition', description: 'La fiche de mission affiche le formateur sollicité et le statut actuel.', image: image('propose-mission-4'), consequence: 'L’OF peut suivre l’avancement sans recréer la mission.' },
      { title: 'Ce que voit le formateur', description: 'Une proposition envoyée dans Clementplane apparaît dans son espace Missions.', image: image('cross-mission-1'), consequence: 'Le formateur peut ouvrir la proposition et vérifier les détails avant de répondre.' },
      { title: 'Consulter avant de répondre', description: 'Le formateur vérifie la formation, le lieu, les dates et les horaires.', image: image('cross-mission-2'), consequence: 'Sa réponse mettra ensuite à jour le suivi de la mission côté OF.' },
    ],
  },
  {
    id: 'respond-to-proposal',
    title: 'Répondre à une proposition de mission',
    introduction: 'Consultez une proposition, répondez et distinguez clairement acceptation et affectation définitive.',
    category: 'Missions',
    audiences: ['trainer'],
    public: false,
    duration: '3 min',
    pdf: pdf('Clementplane_Tutoriel_Repondre_Proposition_Formateur'),
    steps: [
      { title: 'Repérer la proposition', description: 'Une mission nécessitant votre réponse apparaît dans votre liste.', image: image('cross-mission-1'), consequence: 'La mission n’est pas encore confirmée.' },
      { title: 'Vérifier les détails', description: 'Contrôlez le lieu, les dates, les horaires et la formation demandée.', image: image('cross-mission-2'), consequence: 'Vous pouvez décider avec les informations essentielles.' },
      { title: 'Accepter la proposition', description: 'Validez votre réponse positive dans Clementplane.', image: image('cross-mission-3'), consequence: 'L’OF est informé, mais doit encore vous affecter définitivement.' },
      { title: 'Vérifier la confirmation', description: 'Lorsque l’OF vous affecte, la mission passe à l’état confirmé.', image: image('cross-mission-7'), consequence: 'Le processus est terminé et la mission rejoint votre planning.' },
    ],
  },
  {
    id: 'finalize-assignment',
    title: 'Finaliser l’affectation d’un formateur',
    introduction: 'Traitez une réponse positive et confirmez réellement le formateur retenu sur la mission.',
    category: 'Parcours croisés',
    audiences: ['organization', 'trainer'],
    public: false,
    duration: '3 min',
    pdf: pdf('Clementplane_Tutoriel_Finaliser_Affectation_OF'),
    steps: [
      { title: 'Voir la réponse reçue', description: 'La fiche indique que le formateur a accepté la proposition.', image: image('cross-mission-4'), consequence: 'L’acceptation reste une réponse : l’OF doit encore confirmer l’affectation.' },
      { title: 'Lancer l’affectation', description: 'Relisez le formateur sélectionné puis confirmez l’action.', image: image('cross-mission-5'), consequence: 'La confirmation attribue officiellement la mission à ce formateur.' },
      { title: 'Contrôler le résultat côté OF', description: 'La mission affiche désormais le formateur affecté.', image: image('cross-mission-6'), consequence: 'Le planning et le suivi de l’organisme utilisent cette affectation.' },
      { title: 'Ce qui change côté formateur', description: 'La mission apparaît comme confirmée dans son espace.', image: image('cross-mission-7'), consequence: 'Le formateur sait que le processus d’affectation est terminé.' },
    ],
  },
  {
    id: 'accept-and-assign',
    title: 'Accepter une proposition et finaliser la mission',
    introduction: 'Suivez le parcours complet : réponse du formateur, notification de l’OF, affectation et confirmation finale.',
    category: 'Parcours croisés',
    audiences: ['organization', 'trainer'],
    public: true,
    duration: '5 min',
    pdf: pdf('Clementplane_Tutoriel_Accepter_Proposition_Mission'),
    steps: [
      { title: 'Ouvrir la proposition', description: 'Le formateur consulte la mission nécessitant sa réponse.', image: image('cross-mission-1'), consequence: 'Il peut vérifier les informations avant de s’engager.' },
      { title: 'Contrôler les informations', description: 'Le formateur vérifie la formation, le lieu, les dates et les horaires.', image: image('cross-mission-2'), consequence: 'La réponse sera enregistrée dans l’historique de la mission.' },
      { title: 'Accepter', description: 'Le formateur valide sa réponse positive.', image: image('cross-mission-3'), consequence: 'L’OF reçoit la réponse ; la mission n’est pas encore définitivement affectée.' },
      { title: 'Voir la réponse côté OF', description: 'L’organisme retrouve l’acceptation dans la fiche de mission.', image: image('cross-mission-4'), consequence: 'L’OF doit encore sélectionner et affecter le formateur.' },
      { title: 'Confirmer l’affectation', description: 'L’OF confirme le formateur retenu.', image: image('cross-mission-5'), consequence: 'La mission lui est officiellement attribuée.' },
      { title: 'Vérifier côté OF', description: 'La fiche affiche le formateur affecté.', image: image('cross-mission-6'), consequence: 'La mission est intégrée au planning de l’organisme.' },
      { title: 'Vérifier côté formateur', description: 'Le formateur retrouve la mission confirmée.', image: image('cross-mission-7'), consequence: 'Le parcours est terminé des deux côtés.' },
    ],
  },
  {
    id: 'organization-planning',
    title: 'Consulter le planning des missions',
    introduction: 'Visualisez les missions de votre organisme et repérez rapidement leur situation.',
    category: 'Planning',
    audiences: ['organization'],
    public: false,
    duration: '2 min',
    pdf: pdf('Clementplane_Tutoriel_Consulter_Planning_OF'),
    steps: [
      { title: 'Ouvrir « Planning »', description: 'Le calendrier affiche les missions de la période sélectionnée.', image: image('planning-of-1'), consequence: 'Les statuts permettent de distinguer les missions affectées de celles restant à traiter.' },
      { title: 'Changer de période', description: 'Utilisez les flèches ou « Aujourd’hui » pour naviguer.', image: image('planning-of-1'), consequence: 'Le planning se recharge sur la période choisie.' },
      { title: 'Filtrer l’affichage', description: 'Ciblez un formateur ou un statut.', image: image('planning-of-1'), consequence: 'Les filtres ne modifient aucune mission.' },
      { title: 'Ouvrir une mission', description: 'Cliquez sur une intervention pour accéder à son détail.', image: image('planning-of-1'), consequence: 'Vous retrouvez les dates, le formateur et les actions disponibles.' },
    ],
  },
  {
    id: 'follow-missions',
    title: 'Suivre les missions de mon organisme',
    introduction: 'Retrouvez les missions, comprenez leur statut et identifiez l’action suivante.',
    category: 'Missions',
    audiences: ['organization'],
    public: false,
    duration: '3 min',
    pdf: pdf('Clementplane_Tutoriel_Suivre_Missions_OF'),
    steps: [
      { title: 'Ouvrir « Missions »', description: 'La liste regroupe les interventions de votre organisme.', image: image('follow-missions-1'), consequence: 'Les filtres changent uniquement l’affichage.' },
      { title: 'Ouvrir une mission à pourvoir', description: 'La fiche indique qu’aucun formateur n’est encore affecté.', image: image('create-mission-4'), consequence: 'Vous pouvez lancer la recherche depuis cette mission.' },
      { title: 'Repérer une proposition en attente', description: 'La fiche conserve la trace du formateur sollicité.', image: image('propose-mission-4'), consequence: 'La mission attend une réponse ou une mise à jour de votre part.' },
      { title: 'Vérifier l’affectation', description: 'Le détail confirme le formateur retenu.', image: image('cross-mission-6'), consequence: 'La mission est planifiée côté OF et visible côté formateur.' },
    ],
  },
  {
    id: 'import-trainers',
    title: 'Importer plusieurs formateurs',
    introduction: 'Ajoutez un réseau existant à partir du modèle Excel ou d’un fichier CSV contrôlé.',
    category: 'Formateurs',
    audiences: ['organization'],
    public: false,
    duration: '3 min',
    pdf: pdf('Clementplane_Tutoriel_Importer_Formateurs'),
    steps: [
      { title: 'Télécharger le modèle', description: 'Utilisez le modèle Clementplane et conservez les intitulés des colonnes.', image: image('import-trainers-1'), consequence: 'Vous partez d’un fichier compatible.' },
      { title: 'Compléter le fichier', description: 'Le prénom et le nom sont obligatoires ; séparez les compétences par un point-virgule.', image: image('import-trainers-1'), consequence: 'Les valeurs inconnues pourront être signalées lors du contrôle.' },
      { title: 'Choisir le fichier', description: 'Déposez un fichier Excel .xlsx ou CSV.', image: image('import-trainers-1'), consequence: 'Le fichier est chargé pour contrôle, sans création immédiate.' },
      { title: 'Analyser avant d’importer', description: 'Examinez les lignes et les anomalies signalées.', image: image('import-trainers-1'), consequence: 'Rien n’est enregistré avant la validation finale.' },
    ],
  },
  {
    id: 'manage-account',
    title: 'Gérer mon compte Clementplane',
    introduction: 'Mettez à jour vos informations personnelles et les préférences liées à votre compte.',
    category: 'Compte',
    audiences: ['organization', 'trainer'],
    public: false,
    duration: '2 min',
    pdf: pdf('Clementplane_Tutoriel_Gerer_Mon_Compte'),
    steps: [
      { title: 'Ouvrir « Paramètres »', description: 'Le menu mène à la page « Mon compte ».', image: image('account-1'), consequence: 'Vous accédez aux informations rattachées à votre connexion.' },
      { title: 'Modifier prénom et nom', description: 'Corrigez les informations puis cliquez sur « Enregistrer ».', image: image('account-1'), consequence: 'Le nouveau nom sera utilisé dans votre espace.' },
      { title: 'Vérifier l’adresse de connexion', description: 'Votre adresse actuelle est affichée dans le compte.', image: image('account-1'), consequence: 'Un changement peut nécessiter une confirmation de sécurité.' },
      { title: 'Consulter les réglages', description: 'Faites défiler la page pour voir les préférences disponibles.', image: image('account-1'), consequence: 'Les réglages s’appliquent uniquement à votre compte.' },
    ],
  },
  {
    id: 'find-help',
    title: 'Trouver de l’aide dans Clementplane',
    introduction: 'Accédez aux guides, à la FAQ et au formulaire de contact depuis l’application.',
    category: 'Aide',
    audiences: ['organization', 'trainer'],
    public: false,
    duration: '2 min',
    pdf: pdf('Clementplane_Tutoriel_Trouver_Aide_FAQ'),
    steps: [
      { title: 'Ouvrir « Découvrir Clementplane »', description: 'Le contenu s’adapte automatiquement à votre profil.', image: image('help-1'), consequence: 'Vous obtenez les explications correspondant à votre espace.' },
      { title: 'Consulter les guides', description: 'Ouvrez le tutoriel correspondant à l’action recherchée.', image: image('help-1'), consequence: 'Le carrousel montre chaque étape et sa conséquence.' },
      { title: 'Rechercher dans la FAQ', description: 'Saisissez un mot-clé ou parcourez les thèmes.', image: image('help-1'), consequence: 'Vous pouvez vérifier rapidement une règle ou un fonctionnement.' },
      { title: 'Contacter Clementplane', description: 'Choisissez une catégorie et décrivez précisément votre demande.', image: image('help-1'), consequence: 'La demande est enregistrée avec le contexte utile de votre compte.' },
    ],
  },
];

export function getTutorialsForAudience(audience) {
  return tutorialLibrary.filter((tutorial) => tutorial.audiences.includes(audience));
}

export function getPublicTutorials() {
  return tutorialLibrary.filter((tutorial) => tutorial.public);
}
