import { test, expect as baseExpect } from '@playwright/test';
import fs from 'node:fs';
const expect=baseExpect.configure({timeout:30000});
const fixtureDir=process.env.E2E_PERSONAL_DATA_DIR;
test.skip(!fixtureDir,'Explicit isolated test fixtures required; no production credentials.');
for(const width of [1440,390])test(`connected private mission lifecycle ${width}px`,async({page})=>{
 test.setTimeout(300000);
 const c=JSON.parse(fs.readFileSync(fixtureDir+'credentials.json'));const k=JSON.parse(fs.readFileSync(fixtureDir+'public-key.json'));const sessions=JSON.parse(fs.readFileSync(fixtureDir+'sessions.json'));
 expect(c.project).not.toBe('hctvkynrgmnxjynbncdi');expect(c.project).toBe(process.env.E2E_PROJECT_REF);
 let notifications=0;
 await page.route('**/functions/v1/**',route=>{notifications++;return route.abort();});
 await page.addInitScript(({project,session})=>{localStorage.setItem(`sb-${project}-auth-token`,JSON.stringify(session));sessionStorage.setItem('timeforma_active_space','trainer');},{project:c.project,session:sessions[0]});
 await page.setViewportSize({width,height:950});
 await page.goto('/formateur/missions');
 await expect(page.getByRole('heading',{name:'Mes missions',exact:true})).toBeVisible({timeout:30000});
 await page.getByRole('link',{name:'Ajouter une mission',exact:true}).click();
 const title=`Recette connectée fictive ${width} ${Date.now()}`;
 await page.getByLabel('Client final *').fill('Entreprise cliente fictive');
 await page.getByLabel('Formation').fill(title);
 await page.getByLabel('Date 1',{exact:true}).fill('2026-10-25');
 await page.getByLabel('Début 1',{exact:true}).fill('09:00');await page.getByLabel('Fin 1',{exact:true}).fill('12:00');
 await page.getByRole('button',{name:'Ajouter une date'}).click();await page.getByLabel('Date 2',{exact:true}).fill('2026-10-26');
 await page.getByLabel('Donneur d’ordre').fill('Client de recette fictif');
 await page.getByLabel('Nom du site').fill('Centre de recette');
 await page.getByLabel('Adresse').fill('10 rue de la Formation');
 await page.getByLabel('Code postal *').fill('93200');
 await page.getByLabel('Ville *').fill('Saint-Denis');
 await page.getByLabel('Rémunération HT (€)').fill('250');await page.getByLabel('Unité').selectOption('day');
 await page.getByLabel('Notes privées').fill('Note fictive réservée au formateur');
 await page.getByRole('button',{name:'Enregistrer la mission',exact:true}).click();
 const addDialog=page.getByRole('dialog',{name:'Ajouter ce donneur d’ordre à Mes OF ?'});if(await addDialog.isVisible())await page.getByRole('button',{name:'Non, merci'}).click();
 await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();const detail=page.url();
 await page.reload();await expect(page.getByText('250 € HT / jour',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Modifier',exact:true}).click();await page.getByLabel('Formation').fill(title+' modifiée');
 await page.getByRole('button',{name:'Enregistrer les modifications'}).click();await expect(page.getByRole('heading',{name:title+' modifiée'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`test-results/connected-personal-${width}.png`,fullPage:true});
 await page.goto('/formateur/disponibilites');if(width<600)await page.getByRole('button',{name:/25 Mission confirmée/}).click();
 const link=page.locator(`a[href="${new URL(detail).pathname}"]`).first();await expect(link).toBeVisible();await link.click();await expect(page.getByRole('heading',{name:title+' modifiée'})).toBeVisible();
 await page.goto('/formateur/planning');await expect(page.locator('.trainer-planning-mini').filter({hasText:title+' modifiée'})).toHaveCount(2);
 await page.goto(detail);await page.getByRole('button',{name:'Annuler la mission',exact:true}).click();await page.getByRole('button',{name:'Confirmer l’annulation',exact:true}).click();await expect(page.getByText('Annulée',{exact:true})).toBeVisible();
 const id=new URL(detail).pathname.split('/').at(-1);
 const denied=await page.request.get(`${k.url}/rest/v1/trainer_personal_missions?id=eq.${id}&select=id`,{headers:{apikey:k.key,Authorization:`Bearer ${sessions[1].access_token}`}});expect(await denied.json()).toEqual([]);
 expect(notifications).toBe(0);
});
